# Generated by Django 4.1.6 on 2023-02-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_contract_client_alter_event_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="status",
        ),
        migrations.AddField(
            model_name="contract",
            name="signed_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="company_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
