# Generated by Django 4.1.6 on 2023-02-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_client_date_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
