# Generated by Django 4.1.7 on 2023-03-07 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_alter_event_event_status_alter_eventstatus_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventstatus",
            options={"verbose_name_plural": "Event status"},
        ),
    ]
